############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Contact"
url = "/contact"
weight = 3

[[main]]
weight = 4
name = "Previously..."
url = "/previously"

[[main]]
weight = 5
name = "Currently..."
url = "/currently"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Contact"
url = "/contact"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3

[[footer]]
name = "Copyright"
url = "/copyright"
weight = 3
